package de.oliver.fancyholograms.hologram.nms;

public enum MappingKeys1_19_4 {
    DISPLAY__DATA_TRANSFORMATION_INTERPOLATION_DURATION_ID,
    DISPLAY__DATA_TRANSFORMATION_INTERPOLATION_START_DELTA_TICKS_ID,
    TEXT_DISPLAY__DATA_LINE_WIDTH_ID,
    TEXT_DISPLAY__DATA_BACKGROUND_COLOR_ID
}
